name: file_selector_android
publish_to: none
description: Android implementation of the file_selector package.
repository: https://github.com/flutter/packages/tree/main/packages/file_selector/file_selector_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+file_selector%22
version: 0.5.1+12

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

flutter:
  plugin:
    implements: file_selector
    platforms:
      android:
        dartPluginClass: FileSelectorAndroid
        package: dev.flutter.packages.file_selector_android
        pluginClass: FileSelectorAndroidPlugin

dependencies:
  file_selector_platform_interface: 
    git: https://github.com/kumsumit/file_selector_platform_interface.git
  flutter:
    sdk: flutter
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git

topics:
  - files
  - file-selection
  - file-selector
